version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies (none needed for static HTML)
  build:
    commands:
      - echo Build started on `date`
      - echo No actual build steps needed for static HTML
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*.html'
